export type DirectoryConfidenceTier = 'publishable' | 'needs_review'

export interface CommunityDirectorySeed {
  id: string
  name: string
  slug: string
  description: string
  category: string
  cityName: string
  citySlug: string
  usualArea: string
  usualSchedule: string
  joinPlatform: string
  communityLink: string
  websiteUrl?: string
  sourceUrl: string
  sourceLabel: string
  vibeTags: string[]
  priceType: string
  beginnerFriendly: boolean
  soloFriendly: boolean
  bestFor: string
  confidenceTier: DirectoryConfidenceTier
  lastVerifiedAt: string
  coverImage?: string
}

export const SINGAPORE_COMMUNITY_DIRECTORY_SEED: CommunityDirectorySeed[] = [
  {
    id: 'seed-fast-and-free-running-club',
    name: 'Fast and Free Running Club',
    slug: 'fast-and-free-running-club',
    description:
      'A Singapore running community built around regular group runs and a clear public club identity.',
    category: 'running',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Central Singapore',
    usualSchedule: 'Recurring community runs',
    joinPlatform: 'website',
    communityLink: 'https://www.fastandfree.sg/',
    websiteUrl: 'https://www.fastandfree.sg/',
    sourceUrl: 'https://www.fastandfree.sg/',
    sourceLabel: 'Official website',
    vibeTags: ['run_club', 'social', 'recurring'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Runners who want a known local crew before showing up.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-running-department',
    name: 'Running Department',
    slug: 'running-department',
    description:
      'A long-running Singapore run community with public group-run discovery and strong local recognition.',
    category: 'running',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'CBD / Central Singapore',
    usualSchedule: 'Weekly community runs',
    joinPlatform: 'website',
    communityLink: 'https://www.runningdepartment.com/',
    websiteUrl: 'https://www.runningdepartment.com/',
    sourceUrl: 'https://www.runningdepartment.com/',
    sourceLabel: 'Official website',
    vibeTags: ['run_club', 'social', 'recurring'],
    priceType: 'free',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a recognizable run crew with regular sessions.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-zephyr-running-club',
    name: 'Zephyr Running Club',
    slug: 'zephyr-running-club',
    description:
      'A Singapore run club with an official web presence and a community-first running identity.',
    category: 'running',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Recurring runs',
    joinPlatform: 'website',
    communityLink: 'https://www.zephyrrunningclub.com/',
    websiteUrl: 'https://www.zephyrrunningclub.com/',
    sourceUrl: 'https://www.zephyrrunningclub.com/',
    sourceLabel: 'Official website',
    vibeTags: ['run_club', 'training', 'recurring'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Runners looking for a structured local running community.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-mr25',
    name: 'MR25',
    slug: 'mr25',
    description:
      'A MacRitchie-linked running club for runners who want a more established endurance community.',
    category: 'running',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'MacRitchie',
    usualSchedule: 'Regular club runs',
    joinPlatform: 'website',
    communityLink: 'https://mr25.org.sg/',
    websiteUrl: 'https://mr25.org.sg/',
    sourceUrl: 'https://mr25.org.sg/',
    sourceLabel: 'Official website',
    vibeTags: ['run_club', 'trail', 'experienced'],
    priceType: 'membership',
    beginnerFriendly: false,
    soloFriendly: true,
    bestFor: 'Runners who are comfortable with endurance or trail-oriented groups.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-fitfam-singapore',
    name: 'FitFam Singapore',
    slug: 'fitfam-singapore',
    description:
      'A public fitness community focused on accessible group workouts and social accountability.',
    category: 'outdoor_fitness',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Recurring outdoor workouts',
    joinPlatform: 'website',
    communityLink: 'https://www.wefitfam.com/',
    websiteUrl: 'https://www.wefitfam.com/',
    sourceUrl: 'https://www.wefitfam.com/',
    sourceLabel: 'Official website',
    vibeTags: ['outdoor', 'social', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a low-pressure fitness crew instead of a studio class.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-punggol-fit-club',
    name: 'Punggol Fit Club',
    slug: 'punggol-fit-club',
    description:
      'A hyperlocal Punggol fitness community for recurring group workouts and neighborhood accountability.',
    category: 'outdoor_fitness',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Punggol',
    usualSchedule: 'Recurring local workouts',
    joinPlatform: 'website',
    communityLink: 'https://www.punggolfitclub.com/',
    websiteUrl: 'https://www.punggolfitclub.com/',
    sourceUrl: 'https://www.punggolfitclub.com/',
    sourceLabel: 'Official website',
    vibeTags: ['neighborhood', 'outdoor', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Punggol residents who want a nearby group to train with.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-yoga-for-a-change',
    name: 'Yoga for a Change',
    slug: 'yoga-for-a-change',
    description:
      'A mission-led yoga community that makes classes feel like a shared cause, not just another booking.',
    category: 'yoga',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Recurring yoga sessions',
    joinPlatform: 'website',
    communityLink: 'https://www.yogaforachange.com/',
    websiteUrl: 'https://www.yogaforachange.com/',
    sourceUrl: 'https://www.yogaforachange.com/',
    sourceLabel: 'Official website',
    vibeTags: ['mission_led', 'mind_body', 'social'],
    priceType: 'charity',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want yoga with purpose and a softer social entry point.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/organizers-bg.jpg',
  },
  {
    id: 'seed-yoga-seeds',
    name: 'Yoga Seeds',
    slug: 'yoga-seeds',
    description:
      'An outdoor and nature-oriented yoga operator with public classes and a community-friendly wellness angle.',
    category: 'yoga',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Recurring yoga classes',
    joinPlatform: 'website',
    communityLink: 'https://www.yogaseeds.com.sg/',
    websiteUrl: 'https://www.yogaseeds.com.sg/',
    sourceUrl: 'https://www.yogaseeds.com.sg/',
    sourceLabel: 'Official website',
    vibeTags: ['outdoor', 'mind_body', 'beginner'],
    priceType: 'paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who prefer yoga in calmer outdoor or nature-linked settings.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/organizers-bg.jpg',
  },
  {
    id: 'seed-meditate-singapore',
    name: 'Meditate Singapore',
    slug: 'meditate-singapore',
    description:
      'A public meditation community option for people looking for guided mindfulness in Singapore.',
    category: 'meditation',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Recurring meditation sessions',
    joinPlatform: 'website',
    communityLink: 'https://www.meditateinsingapore.org/',
    websiteUrl: 'https://www.meditateinsingapore.org/',
    sourceUrl: 'https://www.meditateinsingapore.org/',
    sourceLabel: 'Official website',
    vibeTags: ['mind_body', 'quiet', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a calmer first step into wellness communities.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/organizers-bg.jpg',
  },
  {
    id: 'seed-singapore-pickleball-meetup',
    name: 'Singapore Pickleball Meetup Group',
    slug: 'singapore-pickleball-meetup-group',
    description:
      'A public Meetup-based pickleball community for people looking for open social play.',
    category: 'pickleball',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Meetup sessions vary',
    joinPlatform: 'meetup',
    communityLink: 'https://www.meetup.com/find/?keywords=pickleball&location=sg--Singapore',
    sourceUrl: 'https://www.meetup.com/find/?keywords=pickleball&location=sg--Singapore',
    sourceLabel: 'Public Meetup search',
    vibeTags: ['open_play', 'social', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a social racquet sport without needing a fixed partner.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-padel-singapore',
    name: 'Padel Singapore',
    slug: 'padel-singapore',
    description:
      'A Singapore padel hub with public booking and discovery paths for people exploring social padel.',
    category: 'tennis',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Open play and bookings vary',
    joinPlatform: 'website',
    communityLink: 'https://padel.sg/',
    websiteUrl: 'https://padel.sg/',
    sourceUrl: 'https://padel.sg/',
    sourceLabel: 'Official website',
    vibeTags: ['racquet', 'open_play', 'social'],
    priceType: 'paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a premium social sport with a clear booking path.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-play-tennis',
    name: 'Play! Tennis',
    slug: 'play-tennis',
    description:
      'A tennis platform with a clear public web path for lessons, programs, and social play discovery.',
    category: 'tennis',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Programs and social play vary',
    joinPlatform: 'website',
    communityLink: 'https://playtennis.sg/',
    websiteUrl: 'https://playtennis.sg/',
    sourceUrl: 'https://playtennis.sg/',
    sourceLabel: 'Official website',
    vibeTags: ['racquet', 'skills', 'social'],
    priceType: 'paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want a structured path into tennis without organizing a group themselves.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-singapore-social-badminton',
    name: 'Singapore Social Badminton',
    slug: 'singapore-social-badminton',
    description:
      'A public social badminton discovery path for casual players looking for games in Singapore.',
    category: 'badminton',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Meetup sessions vary',
    joinPlatform: 'meetup',
    communityLink: 'https://www.meetup.com/find/?keywords=badminton&location=sg--Singapore',
    sourceUrl: 'https://www.meetup.com/find/?keywords=badminton&location=sg--Singapore',
    sourceLabel: 'Public Meetup search',
    vibeTags: ['open_play', 'social', 'casual'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Casual players who want to find a game without a fixed group.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-rapha-cycling-club-singapore',
    name: 'Rapha Cycling Club Singapore',
    slug: 'rapha-cycling-club-singapore',
    description:
      'A premium cycling community with official club infrastructure and Singapore ride discovery.',
    category: 'cycling',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Club rides vary',
    joinPlatform: 'website',
    communityLink: 'https://www.rapha.cc/',
    websiteUrl: 'https://www.rapha.cc/',
    sourceUrl: 'https://www.rapha.cc/',
    sourceLabel: 'Official website',
    vibeTags: ['cycling_club', 'premium', 'experienced'],
    priceType: 'membership',
    beginnerFriendly: false,
    soloFriendly: true,
    bestFor: 'Road cyclists who want an established club structure.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-anza-cycling',
    name: 'ANZA Cycling',
    slug: 'anza-cycling',
    description:
      'An established Singapore cycling club with formal ride organization and community membership.',
    category: 'cycling',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Regular club rides',
    joinPlatform: 'website',
    communityLink: 'https://anza.org.sg/sports/cycling/',
    websiteUrl: 'https://anza.org.sg/sports/cycling/',
    sourceUrl: 'https://anza.org.sg/sports/cycling/',
    sourceLabel: 'Official website',
    vibeTags: ['cycling_club', 'membership', 'experienced'],
    priceType: 'membership',
    beginnerFriendly: false,
    soloFriendly: true,
    bestFor: 'Cyclists who want organized club rides and membership structure.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-five45-cycling-club',
    name: 'FIVE45 Cycling Club',
    slug: 'five45-cycling-club',
    description:
      'A Singapore cycling club with a clear public identity for riders looking for group rides.',
    category: 'cycling',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Club rides vary',
    joinPlatform: 'website',
    communityLink: 'https://five45.cc/',
    websiteUrl: 'https://five45.cc/',
    sourceUrl: 'https://five45.cc/',
    sourceLabel: 'Official website',
    vibeTags: ['cycling_club', 'social', 'training'],
    priceType: 'free_paid',
    beginnerFriendly: false,
    soloFriendly: true,
    bestFor: 'Cyclists who want a local club rather than solo rides.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
  {
    id: 'seed-sgtrek',
    name: 'SGTREK',
    slug: 'sgtrek',
    description:
      'An outdoor and trekking operator with public trip listings for people who want organized hikes.',
    category: 'hiking',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore / regional outdoors',
    usualSchedule: 'Trips and hikes vary',
    joinPlatform: 'website',
    communityLink: 'https://sgtrek.com/',
    websiteUrl: 'https://sgtrek.com/',
    sourceUrl: 'https://sgtrek.com/',
    sourceLabel: 'Official website',
    vibeTags: ['outdoors', 'guided', 'social'],
    priceType: 'paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want the outdoors without planning the route themselves.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-adventure-lovers-singapore',
    name: 'Adventure Lovers Meetup Singapore',
    slug: 'adventure-lovers-meetup-singapore',
    description:
      'A public outdoor Meetup discovery path for hikes, walks, and adventure-oriented social plans.',
    category: 'hiking',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Meetup sessions vary',
    joinPlatform: 'meetup',
    communityLink: 'https://www.meetup.com/find/?keywords=hiking&location=sg--Singapore',
    sourceUrl: 'https://www.meetup.com/find/?keywords=hiking&location=sg--Singapore',
    sourceLabel: 'Public Meetup search',
    vibeTags: ['outdoors', 'social', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Solo joiners who want outdoor plans with other people.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-boulder-without-borders',
    name: 'Boulder Without Borders',
    slug: 'boulder-without-borders',
    description:
      'A public-facing climbing community candidate for social bouldering and inclusive climbing meetups.',
    category: 'climbing',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Community climbs vary',
    joinPlatform: 'website',
    communityLink: 'https://www.boulderwithoutborders.com/',
    websiteUrl: 'https://www.boulderwithoutborders.com/',
    sourceUrl: 'https://www.boulderwithoutborders.com/',
    sourceLabel: 'Official website',
    vibeTags: ['climbing', 'inclusive', 'social'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'Climbers who want a social entry point rather than climbing alone.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-boulderkakis',
    name: 'BoulderKakis',
    slug: 'boulderkakis',
    description:
      'A Singapore climbing community candidate for people looking for bouldering partners and social climbs.',
    category: 'climbing',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Community climbs vary',
    joinPlatform: 'website',
    communityLink: 'https://www.boulderkakis.com/',
    websiteUrl: 'https://www.boulderkakis.com/',
    sourceUrl: 'https://www.boulderkakis.com/',
    sourceLabel: 'Official website',
    vibeTags: ['climbing', 'social', 'beginner'],
    priceType: 'free_paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People who want climbing buddies before committing to a gym routine.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/community-bonds.jpg',
  },
  {
    id: 'seed-metasport',
    name: 'MetaSport',
    slug: 'metasport',
    description:
      'A triathlon and endurance community pathway with public programs and event discovery.',
    category: 'fitness_social',
    cityName: 'Singapore',
    citySlug: 'singapore',
    usualArea: 'Singapore',
    usualSchedule: 'Training and event programs vary',
    joinPlatform: 'website',
    communityLink: 'https://www.metasport.com/',
    websiteUrl: 'https://www.metasport.com/',
    sourceUrl: 'https://www.metasport.com/',
    sourceLabel: 'Official website',
    vibeTags: ['endurance', 'training', 'events'],
    priceType: 'paid',
    beginnerFriendly: true,
    soloFriendly: true,
    bestFor: 'People exploring triathlon or endurance events with a structured operator.',
    confidenceTier: 'publishable',
    lastVerifiedAt: '2026-07-22',
    coverImage: '/images/hosts/run-club-group.jpg',
  },
]

export function getPublicCommunitySeeds() {
  if (!staticCommunitySeedsEnabled()) return []

  return SINGAPORE_COMMUNITY_DIRECTORY_SEED.filter(
    (community) => community.confidenceTier === 'publishable',
  )
}

export function getCommunitySeedBySlug(slug: string) {
  if (!staticCommunitySeedsEnabled()) return null

  return SINGAPORE_COMMUNITY_DIRECTORY_SEED.find((community) => community.slug === slug) ?? null
}

function staticCommunitySeedsEnabled() {
  return process.env.ENABLE_STATIC_COMMUNITY_SEEDS === '1'
}

export function getCommunitySeedConfidenceScore(community: CommunityDirectorySeed) {
  let score = 50
  if (community.sourceLabel.toLowerCase().includes('official')) score += 15
  if (community.communityLink) score += 10
  if (community.usualSchedule) score += 8
  if (community.beginnerFriendly) score += 6
  if (community.soloFriendly) score += 6
  if (community.priceType) score += 5
  return Math.min(score, 100)
}
